---
title: "Our Expectations of Conduct"
output: html_document
---
Please read the following. The official PDF version of this document is [here](files/Expectations for Conduct for the 2019 Paleontological Society Short Course.pdf).

******

&nbsp;

## **Expectations for Conduct** <br/> &nbsp;&nbsp;&nbsp; for the 2019 Paleontological Society Short Course <br/> &nbsp;&nbsp;&nbsp; at the Annual Meeting of the Geological Society of America
&nbsp;

The [Paleontological Society Code of Conduct](https://www.paleosoc.org/paleontological-society-policy-on-non-discrimination-and-code-of-conduct/) applies here, and we wish to particularly emphasize our expectations of behavior for our participants, helpers and organizers at this event.

### Examples of Expected Good Behavior:

- Use welcoming and inclusive language
- Be respectful of different viewpoints and experiences
- Gracefully accept constructive criticism
- Focus on what is best for the community
- Show courtesy and respect towards other community members
  
### Examples of Unacceptable Behavior:

- Written or verbal comments which have the effect of excluding people on the basis of membership of any specific group
- Causing someone to fear for their safety, such as through stalking, following, or intimidation
- Violent threats or language directed against another person
- The display of sexual or violent images
- Unwelcome sexual attention
- Nonconsensual or unwelcome physical contact
- Sustained disruption of talks, events or communications
- Insults or put downs
- Sexist, racist, homophobic, transphobic, ableist, or exclusionary jokes
- Excessive swearing
- Incitement to violence, suicide, or self-harm
- Continuing to initiate interaction (including photography or recording) with someone after being asked to stop
- Publication of private communication without consent

### Consequences of Unacceptable Behavior:

Participants who are asked to stop any inappropriate behavior are expected to comply immediately. If a participant engages in behavior that violates the PS Code of Conduct, the organizers may warn the offender or ask them to leave the event or platform. All violations of the PS Code of Conduct and the GSA’s events code of conduct will be reported to the Paleontological Society Ethics Committee and
GSA leadership.

&nbsp;
&nbsp;

***
***
Some of this text based on (The Carpentries Code of Conduct)[https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html] (licensed CC-BY).
